### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Arlan2191** [yashlamba/handwrite#56]
(Running at Windows x64)
I followed the installation guide from the documentation and confirmed each install. But somehow, when I run
`handwrite ./handwrite.jpg ./`
 in the terminal I get this error:
`Traceback (most recent call last):
  File "c:\users\acer\anaconda3\envs\resnet\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\acer\anaconda3\envs\resnet\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\acer\Anaconda3\envs\Resnet\Scripts\handwrite.exe\__main__.py", line 7, in <module>
  File "c:\users\acer\anaconda3\envs\resnet\lib\site-packages\handwrite\cli.py", line 28, in main
    SVGtoTTF().convert(directory, args.output, args.config)
  File "c:\users\acer\anaconda3\envs\resnet\lib\site-packages\handwrite\svgtottf.py", line 23, in convert
    outfile,
  File "c:\users\acer\anaconda3\envs\resnet\lib\subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\acer\anaconda3\envs\resnet\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "c:\users\acer\anaconda3\envs\resnet\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by yashlamba** [comment]
Can you make sure you can call fontforge from the CLI?
Run: `fontforge -h` in the terminal.
